/**
 * Mailbox Import Service - provider-agnostic bulk import orchestration.
 *
 * The flow:
 *   1. Controller resolves the provider via the registry.
 *   2. Provider lists the customer's mailboxes (with credentials).
 *   3. This service filters to selected remoteIds, encrypts credentials,
 *      upserts ConnectedAccount rows, kicks off Mailbox provisioning.
 *
 * Why this lives here, not in each provider:
 *   - Encryption + DB writes happen in ONE place. Easier to audit.
 *   - Provisioning side-effects are uniform across resellers.
 *   - Providers stay pure: input apiKey + ids → output credential bundle.
 *     A buggy provider can't accidentally leak plaintext to the DB.
 *
 * Idempotency:
 *   - If a ConnectedAccount with the same (org, email) already exists, we
 *     UPDATE its credentials instead of failing. This makes the import
 *     safe to re-run (e.g., after Zapmail rotates an app password).
 *   - Provisioning is itself idempotent - re-running creates no duplicates.
 */

import { prisma } from '../prisma';
import { logger } from './observabilityService';
import { encrypt } from '../utils/encryption';
import { provisionMailboxForConnectedAccount } from './mailboxProvisioningService';
import { getSequencerSettings } from './sequencerSettingsService';
import type {
    BulkImportResult,
    BulkImportResultItem,
    MailboxImportProvider,
    RemoteMailboxCredential,
} from './mailboxImportProviders/types';

/**
 * SMTP/IMAP host defaults per provider. Resellers don't return these in
 * the credential bundle (they're well-known constants), so we set them
 * here based on the mailbox's underlying provider (google or microsoft).
 *
 * Kept in this module instead of a config file so the entire bulk-import
 * surface is auditable in one read.
 */
const SMTP_DEFAULTS: Record<'google' | 'microsoft', {
    smtp_host: string; smtp_port: number;
    imap_host: string; imap_port: number;
}> = {
    google: {
        smtp_host: 'smtp.gmail.com',
        smtp_port: 587,
        imap_host: 'imap.gmail.com',
        imap_port: 993,
    },
    microsoft: {
        smtp_host: 'smtp.office365.com',
        smtp_port: 587,
        imap_host: 'outlook.office365.com',
        imap_port: 993,
    },
};

interface ImportArgs {
    organizationId: string;
    provider: MailboxImportProvider;
    apiKey: string;
    /** Remote IDs (provider-side identifiers) to import. If omitted, imports
     *  every mailbox returned by the provider. */
    remoteIds?: string[];
}

/**
 * Run the full import pipeline. Returns a per-mailbox result so the UI can
 * show "78 imported, 12 already connected, 10 not ready (no app password yet)".
 *
 * Errors at any per-mailbox step land on that item's record - they NEVER
 * abort the whole batch. A partial failure with one bad mailbox shouldn't
 * block the other 99.
 */
export async function runBulkImport(args: ImportArgs): Promise<BulkImportResult> {
    const { organizationId, provider, apiKey, remoteIds } = args;

    if (!provider.isImplemented) {
        throw new Error(`Provider "${provider.key}" is not yet implemented`);
    }

    // 1. Pull the full inventory from the reseller.
    const allRemote = await provider.listMailboxes(apiKey);

    // 2. Filter to selected ids (or take all).
    const selected: RemoteMailboxCredential[] = remoteIds && remoteIds.length > 0
        ? allRemote.filter(m => remoteIds.includes(m.remoteId))
        : allRemote;

    const items: BulkImportResultItem[] = [];
    const orgSettings = await getSequencerSettings(organizationId);
    const defaultDailyLimit = orgSettings.default_daily_limit;

    for (const remote of selected) {
        // Skip rows the reseller hasn't finished provisioning yet - no
        // app password = nothing to connect with.
        if (!remote.appPassword) {
            items.push({
                remoteId: remote.remoteId,
                email: remote.email,
                status: 'skipped',
                error: 'App password not yet generated by reseller (mailbox still being set up)',
            });
            continue;
        }

        const defaults = SMTP_DEFAULTS[remote.provider];
        if (!defaults) {
            items.push({
                remoteId: remote.remoteId,
                email: remote.email,
                status: 'failed',
                error: `Unsupported underlying provider: ${remote.provider}`,
            });
            continue;
        }

        try {
            const existing = await prisma.connectedAccount.findUnique({
                where: { organization_id_email: { organization_id: organizationId, email: remote.email } },
            });

            const credentialFields = {
                provider: remote.provider,
                smtp_host: defaults.smtp_host,
                smtp_port: defaults.smtp_port,
                smtp_username: remote.email,
                smtp_password: encrypt(remote.appPassword),
                imap_host: defaults.imap_host,
                imap_port: defaults.imap_port,
                connection_status: 'active',
                last_error: null,
                display_name: remote.displayName || existing?.display_name || null,
                // Tag the row with the reseller key so the operator can filter
                // mailboxes by source ('zapmail' / 'premium_inboxes' / etc.).
                // Re-importing an existing row OVERWRITES the source tag -
                // last-touched-by wins, which is the right behavior because
                // updating credentials means this reseller is now the truth.
                source: provider.key,
            };

            let accountId: string;
            if (existing) {
                // Re-import: update credentials in place. Don't touch
                // OAuth fields - they may still be in use by a legacy
                // connection. Don't reset send-stat counters.
                await prisma.connectedAccount.update({
                    where: { id: existing.id },
                    data: credentialFields,
                });
                accountId = existing.id;
                items.push({
                    remoteId: remote.remoteId,
                    email: remote.email,
                    status: 'updated',
                    connectedAccountId: accountId,
                });
            } else {
                const created = await prisma.connectedAccount.create({
                    data: {
                        ...credentialFields,
                        organization_id: organizationId,
                        email: remote.email,
                        daily_send_limit: defaultDailyLimit,
                    },
                });
                accountId = created.id;
                items.push({
                    remoteId: remote.remoteId,
                    email: remote.email,
                    status: 'imported',
                    connectedAccountId: accountId,
                });
            }

            // Provision shadow Mailbox + Domain row. Idempotent.
            try {
                await provisionMailboxForConnectedAccount({
                    connectedAccountId: accountId,
                    organizationId,
                    email: remote.email,
                    displayName: remote.displayName,
                });
            } catch (provisionErr) {
                // Provisioning failure is recoverable - the reconciliation
                // worker will retry. Mark the row but don't fail the import.
                logger.error(
                    '[MAILBOX_IMPORT] Provisioning failed (will retry)',
                    provisionErr instanceof Error ? provisionErr : new Error(String(provisionErr)),
                    { accountId, email: remote.email },
                );
                await prisma.connectedAccount.update({
                    where: { id: accountId },
                    data: {
                        connection_status: 'provisioning_failed',
                        last_error: `provisioning: ${provisionErr instanceof Error ? provisionErr.message : String(provisionErr)}`,
                    },
                }).catch(() => undefined);
            }
        } catch (err) {
            logger.error(
                '[MAILBOX_IMPORT] Failed to import mailbox',
                err instanceof Error ? err : new Error(String(err)),
                { email: remote.email, providerKey: provider.key },
            );
            items.push({
                remoteId: remote.remoteId,
                email: remote.email,
                status: 'failed',
                error: err instanceof Error ? err.message : String(err),
            });
        }
    }

    return {
        total: selected.length,
        imported: items.filter(i => i.status === 'imported').length,
        updated: items.filter(i => i.status === 'updated').length,
        skipped: items.filter(i => i.status === 'skipped').length,
        failed: items.filter(i => i.status === 'failed').length,
        items,
    };
}
